name: e_commerce_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  country_picker: ^2.0.21
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  glass: ^2.0.0+1
  google_fonts: ^6.2.0
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  lottie: ^2.6.0
  otp_text_field: ^1.1.3
  shimmer: ^3.0.0
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.10.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/

